version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
        interval: daily
    open-pull-requests-limit: 15

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
        interval: daily
    open-pull-requests-limit: 15

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
