require:
  - rubocop-i18n
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

RailsI18n:
  Enabled: true
GetText:
  Enabled: false
