require:
  - rubocop-i18n
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - test/**/*

RailsI18n:
  Enabled: true
GetText:
  Enabled: false

