require:
  - rubocop-i18n
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - test/**/*

I18n/RailsI18n:
  Enabled: true
I18n/GetText:
  Enabled: false

Minitest/MultipleAssertions:
  Max: 10
