require:
  - rubocop-capybara
  - rubocop-i18n
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - test/**/*

I18n/RailsI18n:
  Enabled: true
I18n/GetText:
  Enabled: false

Minitest/MultipleAssertions:
  Max: 10

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Rails/HelperInstanceVariable:
  Enabled: false

# TODO: enable these rules when starting doing i18n

Rails/I18nLocaleTexts:
  Enabled: false

I18n/RailsI18n/DecorateString:
  Enabled: false

# Allow string or symbol array without literal
Style/WordArray:
  EnforcedStyle: brackets
  SupportedStyles:
    - brackets

Style/SymbolArray:
  EnforcedStyle: brackets
  SupportedStyles:
    - brackets

Style/HashSyntax:
  EnforcedShorthandSyntax: either_consistent
