# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.4.2@sha256:a143fd2de1e22c0d2acd9167eb28c7a4a81628e370b94db4a66754824f029b8a
FROM ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION
