# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.4.2@sha256:3246fd81cd4158523c17b66fe0add0d6be11cf238816a579429ba5db39e8af95
FROM ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION
