# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.4.5@sha256:21f3d650521a75cd67f14a79bc112f44f75133be3dd42b4d63a501ec93acd45a
FROM ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION
