name: Lint & test

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
       # Install the version defined in .ruby-version
        uses: ruby/setup-ruby@v1
        with:
            bundler-cache: true
      - name: Install dependencies
        run: bundle install
